### ISSUE TITLE
Add ability to skip nodata values in calcPerSegmentStatsTiled

### ISSUE THREAD

**Issue by gillins** [ubarsc/pyshepseg#19]
Currently there seems that all pixels in the `imgfile` get processed whether they are nodata or not. Seems more complete to skip these values (if nodata is set, probably no change to current behaviour if it is not set on the input band).

Will need another dictionary to track the number of nodata pixels encountered for each segment and use this in `checkSegComplete` along with the current histogram to determine if all pixels for a segment have been seen.

Also will need a way of dealing with no valid pixels for a segment in `SegmentStats`. And a value to set for the stats when there are no valid pixels (-999, 0, or some user supplied value).

**Comment by neilflood** [comment]
I think you are right. 

I do note that it is not a problem when calculating stats on the imagery which was used to create the segmentation in the first place (i.e. the most common situation). However, as discussed before, stats on other associated imagery is also a perfectly valid action, so we should cope with it. 

Any rush? I am happy to ponder this on a day when I feel motivated, but if there is an immediate need, it might be worth prodding me to hurry.
