### ISSUE TITLE
Subsampling logic for tiled segmentation breaks down if there are fewer than 1000000 pixels

### ISSUE THREAD

**Issue by gillins** [ubarsc/pyshepseg#51]
Need to add a check against people doing this.

**Comment by neilflood** [comment]
What are the circumstance in which this occurs? Do you mean the whole image < 1000000, or is this a single tile?
I thought we already had something to prevent tiles being too small......

**Comment by gillins** [comment]
Whole image < 1000000... Pretty unlikely I know, but the error they get is a bit non-intuitive.

**Comment by neilflood** [comment]
Ah, OK, fair enough. Yes, good thinking, thanks. I will have a look, leave it with me.

**Comment by gillins** [comment]
Only if you feel like it. I just put this issue in so I wouldn't forget....

**Comment by gillins** [comment]
I'm not sure whether it is better to 1) raise an error 2) or cope and just get 100% of the pixels. Whatever is easiest would be fine.
