### ISSUE TITLE
why do I have segments with n_pixels < minSegmentSize ? 

### ISSUE THREAD

**Issue by juan-guerschman** [ubarsc/pyshepseg#59]
I run a segmentation with `minSegmentSize=10000`

I end up with a bunch of small segments anyway. Why? 

It is a small image. A very skewed distribution, very tricky to get a decent histogram. 

```
for i in segments_gdf['n_pixs'].sort_values():
    print(i,end=' ') 
    
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 11 11 11 11 11 11 11 11 11 11 11 11 11 11 11 12 12 12 12 12 12 12 12 12 12 12 12 12 12 13 13 13 13 13 13 13 13 14 14 14 14 14 14 15 15 15 15 15 15 15 15 15 15 15 15 15 16 16 16 16 16 16 16 17 17 17 17 17 17 18 18 18 18 18 18 19 19 19 19 19 19 19 19 19 19 20 20 20 20 20 20 20 20 20 20 22 22 22 22 23 23 23 23 24 24 24 24 24 25 25 25 27 27 27 28 29 29 30 31 31 32 32 32 33 33 33 34 34 34 35 36 36 38 38 39 41 41 41 41 42 42 43 43 44 44 45 45 45 45 47 47 47 48 49 49 50 50 50 50 51 51 51 51 52 53 54 56 58 59 59 61 61 62 62 63 63 65 65 68 68 71 72 72 73 78 84 85 86 86 93 95 96 97 97 98 103 104 104 106 106 107 125 127 134 134 137 139 156 161 163 163 166 174 186 189 191 207 225 235 286 386 404 408 432 442 557 716 822 2398 2646 2727 9458 10018 10030 10105 10260 10316 10473 10559 10637 10874 10900 10902 10914 10920 10976 11052 11218 11301 11356 11539 11758 11762 11849 11935 12263 12316 12484 12517 12592 12685 12688 12866 12870 12910 12924 13149 13150 13192 13352 13375 13389 13403 13450 13604 13729 13835 14037 14104 14129 14335 14352 14360 14425 14904 15022 15029 15115 15377 15523 15612 15616 15684 15690 15758 15772 15829 16013 16084 16086 16245 16532 16816 16963 17199 17327 17403 18025 18223 18247 18267 18400 18820 18840 18853 19071 19074 19224 19475 19513 19782 20189 20247 20647 20921 21018 21474 22150 22173 22411 22442 22626 22800 22899 23056 23223 23538 23687 23734 23928 23959 24256 24658 25106 25388 25545 25553 26195 26513 27019 27191 27341 28662 30804 31031 31571 32023 33952 34207 34478 38894 45728 45875 525177 970533 
```

@gillins @petescarth

**Comment by neilflood** [comment]
Hi @juan-guerschman 
:-)

Probably the main effect going on here (can't tell for sure without the data, etc.) is that as the algorithm merges small segments, it won't merge segments which are too spectrally different. This allows it to preserve small but very distinct segments, even though they are smaller than the minSegmentSize.

This can be controlled using the maxSpectralDiff parameter. It won't merge if two segments are spectrally more different than this amount. The default behaviour is to work out a value for this, based on the cluster centres, and this calculated value is returned in the SegmentationResult object. If you want to start playing around, first find that value, and then pass in something larger. Or you could set this to something huge, effectively disabling the behaviour.

However, this behaviour is there for a reason. Without it, it is very easy to just smear across all the interesting features of the image. So, you should be careful if you start to disable it. 

Of course, it could be something else, but that is my first guess.

**Comment by juan-guerschman** [comment]
gotcha, makes sense. Now I see it in the code.
https://github.com/ubarsc/pyshepseg/blob/0430dd1ba44f8dc945f1493f388395a987be6872/pyshepseg/shepseg.py#L919

yes, the small segments tend to be spectrally very different and it makes sense that they are there.
Thanks!
